### ISSUE TITLE
predefinedValidators is undefined

### ISSUE THREAD

**Issue by charlesamoreira** [wpic/bootstrap.validator.js#1]
OLD:
                        if (regex) {
                            var r;
                            if (typeof(predefinedValidators[regex]) != 'undefined') {
                                r = predefinedValidators[regex]
                            }

NEW:
                        if (regex) {
                            var r;
                            if (typeof(validators[regex]) != 'undefined') {
                                r = validators[regex]
                            }

**Comment by juan-carmona** [comment]
Can i use this in textarea?
